### ISSUE TITLE
Works, but problem compiling csv file.

### ISSUE THREAD

**Issue by MoHabib88** [Trones21/JobSearchScrapeAndApply#1]
Traceback (most recent call last):
  File "oneterm.py", line 37, in <module>
    writer.writerow(job)
  File "/usr/lib/python2.7/csv.py", line 152, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "/usr/lib/python2.7/csv.py", line 148, in _dict_to_list
    + ", ".join([repr(x) for x in wrong_fields]))
ValueError: dict contains fields not in fieldnames: u'stations'

File: "One term All Countries Save to csv.py"

**Comment by MoHabib88** [comment]
added 'stations' to fieldname solved the problem.
